name: chat_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  firebase_auth: ^4.19.0
  firebase_core: ^2.28.0
  flutter:
    sdk: flutter
  flutter_facebook_auth: ^6.0.4
  flutter_riverpod: ^2.5.1
  go_router: ^13.2.2
  google_sign_in: ^6.2.1
  riverpod_annotation: ^2.3.5
  otp_text_field: ^1.1.3
  intl_phone_field: ^3.2.0
  freezed: ^2.5.1
  freezed_annotation: ^2.4.1
  cloud_firestore: ^4.17.0
  animated_notch_bottom_bar: ^1.0.3
  animated_bottom_navigation_bar: ^1.3.3
  intl: ^0.19.0
  firebase_storage: ^11.7.4
  image_picker: ^1.1.0
  path_to_regexp: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10


flutter:
  uses-material-design: true

  assets:
      # - assets/lottie/
      - assets/images/

  # fonts:
  #   - family: Pacifico
  #     fonts:
  #       - asset: assets/fonts/Pacifico-Regular.ttf