// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzYh-hsm82tHxTWU0EyArdVAeSQLIMzLM',
    appId: '1:524078247678:web:6c64414497c6ea0cc3bfaf',
    messagingSenderId: '524078247678',
    projectId: 'chat-app-62300',
    authDomain: 'chat-app-62300.firebaseapp.com',
    storageBucket: 'chat-app-62300.appspot.com',
    measurementId: 'G-GYV7VMJXJK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB4W3U5ubYowXqS303q8zNL__ya8gChv5U',
    appId: '1:524078247678:android:66e703da2bb03f5bc3bfaf',
    messagingSenderId: '524078247678',
    projectId: 'chat-app-62300',
    storageBucket: 'chat-app-62300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCv0hl0FfR1h8vdd_dpNFKCT15JiGTRAiU',
    appId: '1:524078247678:ios:9f05daa43f0c2cc4c3bfaf',
    messagingSenderId: '524078247678',
    projectId: 'chat-app-62300',
    storageBucket: 'chat-app-62300.appspot.com',
    androidClientId: '524078247678-n094ahiu6hvthluhsv0qva28ipt2eitu.apps.googleusercontent.com',
    iosClientId: '524078247678-up58pieh4d7njajulrlvv15kfa0urqho.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
